### ISSUE TITLE
Add "placeholder" in each element in init.conf documentation

### ISSUE THREAD

**Issue by etsardou** [robotics-4-all/device-app-manager#23]

**Comment by etsardou** [comment]
```
link:
params:
  - name: ParamName
    placeholder: ParamPlaceholder
    type: String
    value:
```
